### ISSUE TITLE
Not able to support Java 10

### ISSUE THREAD

**Issue by julianghionoiu** [julianghionoiu/record-and-upload#5] opened 2018-10-31 06:58 UTC
If the candidates try to run the recording capsule with Java 10 installed, they receive the following error:
![pastedimage](https://user-images.githubusercontent.com/5089833/47771196-34b41b00-dcda-11e8-9a46-c8dd19f72656.png)

By the looks of it, the script thing that the Java version is pre java 9, while the real version is greater than Java 9.

**Comment by neomatrix369** [comment] 2018-11-04 09:45
As mentioned, our windows script is not detecting the version string correctly, either the format has changed or something else is the case with the script

**Comment by neomatrix369** [comment] 2018-11-12 15:14
Pls assign it to me @julianghionoiu

**Comment by julianghionoiu** [comment] 2018-11-12 20:12
You need to accept the Github invite first

**Comment by neomatrix369** [comment] 2018-11-12 22:07
Just did, I thought I always had accepted it long ago. So many of the dev-xxx-yyy to remember ;)

**Comment by neomatrix369** [comment] 2018-11-13 00:19
The issue is actually in the individual `record_screen_and_upload.bat` files in each of the `tdl-runner-xxx`

**Comment by neomatrix369** [comment] 2018-11-13 00:30
This post kinda explains what the issue is - https://stackoverflow.com/questions/9116365/windows-batch-file-if-failure-how-can-30000000000000-equal-40000000000

We used quotes to encapsulate the version number - instead I have adopted the answer and going to test it out:

```batch
==>snipped<==
set JAVA_VERSION_9=9

if %JAVA_VERSION% lss %JAVA_VERSION_9% (
   echo "--- Pre-Java 9 detected (Java version %JAVA_VERSION%) ---"
==>snipped<==
```

**Comment by neomatrix369** [comment] 2018-11-13 00:31
Initial test worked for Java 10:
```
D:\tdl-runner-java>record_screen_and_upload.bat

Displaying operating system specific systeminfo...
OS Name:                   Microsoft Windows 10 Enterprise Evaluation
OS Version:                10.0.17134 N/A Build 17134
OS Manufacturer:           Microsoft Corporation
OS Configuration:          Standalone Workstation
OS Build Type:             Multiprocessor Free
BIOS Version:              innotek GmbH VirtualBox, 12/1/2006

D:\tdl-runner-java>for /F "tokens=3" %g in ('java.exe -version 2>&1 | findstr /i "version"') do (set JAVA_FULL_VERSION=%g )

D:\tdl-runner-java>(set JAVA_FULL_VERSION="10.0.2" )

JAVA_FULL_VERSION=10.0.2

JAVA_VERSION=10
"--- Java 9 or higher detected (Java version 10) ---"
"Adding JVM args to the DEFAULT_JVM_OPTS variable, new value set to ''"
"--------------------------------------------------------------------------------------------------------------"

D:\tdl-runner-java>"java.exe" --illegal-access=warn --add-modules=java.xml.bind,java.activation    -jar "D:\tdl-runner-java\\record\record-and-upload-capsule.jar" --config D:\tdl-runner-java\\config\credentials.config --store D:\tdl-runner-java\\record\localstore --sourcecode D:\tdl-runner-java\
WARNING: Illegal reflective access by Capsule (file:/D:/tdl-runner-java/record/record-and-upload-capsule.jar) to field com.sun.jmx.mbeanserver.JmxMBeanServer.mbsInterceptor
INFO  [main]       - Starting recording app
INFO  [main]       - Checking permissions
ERROR [main]       - User does not have enough permissions to upload. Reason: The provided token has expired. (Service: Amazon S3; Status Code: 400; Error Code: ExpiredToken; Request ID: 19271E5E0ADE4AE1)
```

Now will test with other versions of Java and will post responses.

**Comment by neomatrix369** [comment] 2018-11-13 00:49
Pushed changes to https://github.com/julianghionoiu/tdl-lord-of-runners/pull/6, which other repos need to be updated?

**Comment by julianghionoiu** [comment] 2018-11-13 07:44
Just this one, I will do the others.

**Closed as completed** 2018-11-13 08:06 UTC
Labels: bug
